<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[ThisTest2method start sucessfully ]]>
    </line>
    <line>
      <![CDATA[Test 2 is running]]>
    </line>
    <line>
      <![CDATA[ThisTest2method completly successfull ]]>
    </line>
    <line>
      <![CDATA[ThisTest3method start sucessfully ]]>
    </line>
    <line>
      <![CDATA[ThisTest3method is Fail ]]>
    </line>
    <line>
      <![CDATA[ThisTest4method start sucessfully ]]>
    </line>
    <line>
      <![CDATA[Test 4 is running]]>
    </line>
    <line>
      <![CDATA[ThisTest4method completly successfull ]]>
    </line>
    <line>
      <![CDATA[ThisTest1method start sucessfully ]]>
    </line>
    <line>
      <![CDATA[Test 1 is running]]>
    </line>
    <line>
      <![CDATA[ThisTest1method completly successfull ]]>
    </line>
    <line>
      <![CDATA[ThisTest5method start sucessfully ]]>
    </line>
    <line>
      <![CDATA[ThisTest5method is skipped ]]>
    </line>
  </reporter-output>
  <suite started-at="2023-08-09T15:38:27 IST" name="Suite" finished-at="2023-08-09T15:38:28 IST" duration-ms="907">
    <groups>
    </groups>
    <test started-at="2023-08-09T15:38:27 IST" name="Test" finished-at="2023-08-09T15:38:28 IST" duration-ms="907">
      <class name="testNg.ListnerStudy">
        <test-method signature="Test2()[pri:0, instance:testNg.ListnerStudy@5d534f5d]" started-at="2023-08-09T15:38:27 IST" name="Test2" finished-at="2023-08-09T15:38:27 IST" duration-ms="179" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[ThisTest2method start sucessfully ]]>
            </line>
            <line>
              <![CDATA[Test 2 is running]]>
            </line>
            <line>
              <![CDATA[ThisTest2method completly successfull ]]>
            </line>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method signature="Test3()[pri:0, instance:testNg.ListnerStudy@5d534f5d]" started-at="2023-08-09T15:38:27 IST" name="Test3" finished-at="2023-08-09T15:38:27 IST" duration-ms="23" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testNg.ListnerStudy.Test3(ListnerStudy.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[ThisTest3method start sucessfully ]]>
            </line>
            <line>
              <![CDATA[ThisTest3method is Fail ]]>
            </line>
          </reporter-output>
        </test-method> <!-- Test3 -->
        <test-method signature="Test4()[pri:0, instance:testNg.ListnerStudy@5d534f5d]" started-at="2023-08-09T15:38:27 IST" name="Test4" finished-at="2023-08-09T15:38:28 IST" duration-ms="51" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[ThisTest4method start sucessfully ]]>
            </line>
            <line>
              <![CDATA[Test 4 is running]]>
            </line>
            <line>
              <![CDATA[ThisTest4method completly successfull ]]>
            </line>
          </reporter-output>
        </test-method> <!-- Test4 -->
        <test-method signature="Test1()[pri:0, instance:testNg.ListnerStudy@5d534f5d]" started-at="2023-08-09T15:38:28 IST" name="Test1" finished-at="2023-08-09T15:38:28 IST" duration-ms="12" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[ThisTest1method start sucessfully ]]>
            </line>
            <line>
              <![CDATA[Test 1 is running]]>
            </line>
            <line>
              <![CDATA[ThisTest1method completly successfull ]]>
            </line>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method signature="Test5()[pri:0, instance:testNg.ListnerStudy@5d534f5d]" started-at="2023-08-09T15:38:28 IST" name="Test5" finished-at="2023-08-09T15:38:28 IST" depends-on-methods="testNg.ListnerStudy.Test3" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testNg.ListnerStudy.Test5() on instance testNg.ListnerStudy@5d534f5d depends on not successfully finished methods 
[testNg.ListnerStudy.Test3() on instance testNg.ListnerStudy@5d534f5d]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testNg.ListnerStudy.Test5() on instance testNg.ListnerStudy@5d534f5d depends on not successfully finished methods 
[testNg.ListnerStudy.Test3() on instance testNg.ListnerStudy@5d534f5d]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[ThisTest5method is skipped ]]>
            </line>
          </reporter-output>
        </test-method> <!-- Test5 -->
      </class> <!-- testNg.ListnerStudy -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
